/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/v1/auth/register": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Register a new user */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      /** @description User registration data */
      requestBody: {
        content: {
          "application/json": {
            name: string;
            /** Format: email */
            email: string;
            password: string;
          };
        };
      };
      responses: {
        /** @description User registered successfully */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["AuthTokenResponse"];
          };
        };
        400: components["responses"]["400"];
        401: components["responses"]["401"];
        403: components["responses"]["403"];
        404: components["responses"]["404"];
        409: components["responses"]["409"];
        410: components["responses"]["410"];
        422: components["responses"]["422"];
        429: components["responses"]["429"];
        500: components["responses"]["500"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Login a user */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      /** @description User login data */
      requestBody: {
        content: {
          "application/json": {
            /** Format: email */
            email: string;
            password: string;
          };
        };
      };
      responses: {
        /** @description User logged in successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["AuthTokenResponse"];
          };
        };
        400: components["responses"]["400"];
        401: components["responses"]["401"];
        403: components["responses"]["403"];
        404: components["responses"]["404"];
        409: components["responses"]["409"];
        410: components["responses"]["410"];
        422: components["responses"]["422"];
        429: components["responses"]["429"];
        500: components["responses"]["500"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/auth/forgot-password": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Send a password reset email */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      /** @description Email address */
      requestBody: {
        content: {
          "application/json": {
            /** Format: email */
            email: string;
          };
        };
      };
      responses: {
        /** @description Reset link sent if email exists */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        400: components["responses"]["400"];
        401: components["responses"]["401"];
        403: components["responses"]["403"];
        404: components["responses"]["404"];
        409: components["responses"]["409"];
        410: components["responses"]["410"];
        422: components["responses"]["422"];
        429: components["responses"]["429"];
        500: components["responses"]["500"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/auth/reset-password": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Reset password using a token */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      /** @description Token and new password */
      requestBody: {
        content: {
          "application/json": {
            token: string;
            password: string;
          };
        };
      };
      responses: {
        /** @description Password reset successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        400: components["responses"]["400"];
        401: components["responses"]["401"];
        403: components["responses"]["403"];
        404: components["responses"]["404"];
        409: components["responses"]["409"];
        410: components["responses"]["410"];
        422: components["responses"]["422"];
        429: components["responses"]["429"];
        500: components["responses"]["500"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/users/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get current user */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Current user data */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["User"];
          };
        };
        400: components["responses"]["400"];
        401: components["responses"]["401"];
        403: components["responses"]["403"];
        404: components["responses"]["404"];
        409: components["responses"]["409"];
        410: components["responses"]["410"];
        422: components["responses"]["422"];
        429: components["responses"]["429"];
        500: components["responses"]["500"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/packages": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List all available subscription packages */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description List of subscription packages */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["SubscriptionPackageOutput"][];
          };
        };
        400: components["responses"]["400"];
        401: components["responses"]["401"];
        403: components["responses"]["403"];
        404: components["responses"]["404"];
        409: components["responses"]["409"];
        410: components["responses"]["410"];
        422: components["responses"]["422"];
        429: components["responses"]["429"];
        500: components["responses"]["500"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/subscriptions/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get current user active subscription */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Active subscription or null */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Subscription"] | null;
          };
        };
        400: components["responses"]["400"];
        401: components["responses"]["401"];
        403: components["responses"]["403"];
        404: components["responses"]["404"];
        409: components["responses"]["409"];
        410: components["responses"]["410"];
        422: components["responses"]["422"];
        429: components["responses"]["429"];
        500: components["responses"]["500"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/subscriptions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Subscribe to or switch subscription package */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      /** @description Package to subscribe to */
      requestBody: {
        content: {
          "application/json": components["schemas"]["SubscribeInput"];
        };
      };
      responses: {
        /** @description Subscription created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Subscription"];
          };
        };
        400: components["responses"]["400"];
        401: components["responses"]["401"];
        403: components["responses"]["403"];
        404: components["responses"]["404"];
        409: components["responses"]["409"];
        410: components["responses"]["410"];
        422: components["responses"]["422"];
        429: components["responses"]["429"];
        500: components["responses"]["500"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/subscriptions/history": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get subscription history */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Subscription history */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Subscription"][];
          };
        };
        400: components["responses"]["400"];
        401: components["responses"]["401"];
        403: components["responses"]["403"];
        404: components["responses"]["404"];
        409: components["responses"]["409"];
        410: components["responses"]["410"];
        422: components["responses"]["422"];
        429: components["responses"]["429"];
        500: components["responses"]["500"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/admin/stats": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get admin dashboard stats */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Admin dashboard statistics */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["AdminStats"];
          };
        };
        400: components["responses"]["400"];
        401: components["responses"]["401"];
        403: components["responses"]["403"];
        404: components["responses"]["404"];
        409: components["responses"]["409"];
        410: components["responses"]["410"];
        422: components["responses"]["422"];
        429: components["responses"]["429"];
        500: components["responses"]["500"];
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/admin/packages": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List all subscription packages */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description List of subscription packages */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["SubscriptionPackageOutput"][];
          };
        };
        400: components["responses"]["400"];
        401: components["responses"]["401"];
        403: components["responses"]["403"];
        404: components["responses"]["404"];
        409: components["responses"]["409"];
        410: components["responses"]["410"];
        422: components["responses"]["422"];
        429: components["responses"]["429"];
        500: components["responses"]["500"];
      };
    };
    put?: never;
    /** Create a subscription package */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      /** @description Subscription package data */
      requestBody: {
        content: {
          "application/json": components["schemas"]["CreateSubscriptionPackage"];
        };
      };
      responses: {
        /** @description Subscription package created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["SubscriptionPackageOutput"];
          };
        };
        400: components["responses"]["400"];
        401: components["responses"]["401"];
        403: components["responses"]["403"];
        404: components["responses"]["404"];
        409: components["responses"]["409"];
        410: components["responses"]["410"];
        422: components["responses"]["422"];
        429: components["responses"]["429"];
        500: components["responses"]["500"];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/admin/packages/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a subscription package */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Subscription package data */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["SubscriptionPackageOutput"];
          };
        };
        400: components["responses"]["400"];
        401: components["responses"]["401"];
        403: components["responses"]["403"];
        404: components["responses"]["404"];
        409: components["responses"]["409"];
        410: components["responses"]["410"];
        422: components["responses"]["422"];
        429: components["responses"]["429"];
        500: components["responses"]["500"];
      };
    };
    /** Update a subscription package */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      /** @description Subscription package update data */
      requestBody: {
        content: {
          "application/json": components["schemas"]["UpdateSubscriptionPackage"];
        };
      };
      responses: {
        /** @description Subscription package updated */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["SubscriptionPackageOutput"];
          };
        };
        400: components["responses"]["400"];
        401: components["responses"]["401"];
        403: components["responses"]["403"];
        404: components["responses"]["404"];
        409: components["responses"]["409"];
        410: components["responses"]["410"];
        422: components["responses"]["422"];
        429: components["responses"]["429"];
        500: components["responses"]["500"];
      };
    };
    post?: never;
    /** Delete a subscription package */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Subscription package deleted */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        400: components["responses"]["400"];
        401: components["responses"]["401"];
        403: components["responses"]["403"];
        404: components["responses"]["404"];
        409: components["responses"]["409"];
        410: components["responses"]["410"];
        422: components["responses"]["422"];
        429: components["responses"]["429"];
        500: components["responses"]["500"];
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    SubscriptionPackage: {
      id: string;
      name: string;
      maxFolders: number;
      maxNestingLevel: number;
      allowedFileTypes: ("IMAGE" | "VIDEO" | "PDF" | "AUDIO")[];
      maxFileSizeMb: number;
      totalFileLimit: number;
      filesPerFolder: number;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    CreateSubscriptionPackage: {
      name: string;
      maxFolders: number;
      maxNestingLevel: number;
      allowedFileTypes: ("IMAGE" | "VIDEO" | "PDF" | "AUDIO")[];
      maxFileSizeMb: number;
      totalFileLimit: number;
      filesPerFolder: number;
    };
    UpdateSubscriptionPackage: {
      name?: string;
      maxFolders?: number;
      maxNestingLevel?: number;
      allowedFileTypes?: ("IMAGE" | "VIDEO" | "PDF" | "AUDIO")[];
      maxFileSizeMb?: number;
      totalFileLimit?: number;
      filesPerFolder?: number;
    };
    SubscribeInput: {
      packageId: string;
    };
    AuthTokenResponse: {
      accessToken: string;
    };
    User: {
      id: string;
      name: string;
      /** Format: email */
      email: string;
      /** @enum {string} */
      role: "ADMIN" | "USER";
      /** Format: date-time */
      emailVerified?: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    AdminStats: {
      totalUsers: number;
      verifiedUsers: number;
      totalPackages: number;
      dailySignups: {
        date: string;
        count: number;
      }[];
    };
    Subscription: {
      id: string;
      userId: string;
      packageId: string;
      /** Format: date-time */
      startedAt: string;
      endedAt: string | null;
      package: components["schemas"]["SubscriptionPackageOutput"];
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    SubscriptionPackageOutput: {
      id: string;
      name: string;
      maxFolders: number;
      maxNestingLevel: number;
      allowedFileTypes: ("IMAGE" | "VIDEO" | "PDF" | "AUDIO")[];
      maxFileSizeMb: number;
      totalFileLimit: number;
      filesPerFolder: number;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
  };
  responses: {
    /** @description The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing). */
    400: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": {
          error: {
            /**
             * @description A short code indicating the error code returned.
             * @example bad_request
             * @enum {string}
             */
            code: "bad_request";
            /**
             * @description A human readable explanation of what went wrong.
             * @example The requested resource was not found.
             */
            message: string;
          };
        };
      };
    };
    /** @description Although the HTTP standard specifies "unauthorized", semantically this response means "unauthenticated". That is, the client must authenticate itself to get the requested response. */
    401: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": {
          error: {
            /**
             * @description A short code indicating the error code returned.
             * @example unauthorized
             * @enum {string}
             */
            code: "unauthorized";
            /**
             * @description A human readable explanation of what went wrong.
             * @example The requested resource was not found.
             */
            message: string;
          };
        };
      };
    };
    /** @description The client does not have access rights to the content; that is, it is unauthorized, so the server is refusing to give the requested resource. Unlike 401 Unauthorized, the client's identity is known to the server. */
    403: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": {
          error: {
            /**
             * @description A short code indicating the error code returned.
             * @example forbidden
             * @enum {string}
             */
            code: "forbidden";
            /**
             * @description A human readable explanation of what went wrong.
             * @example The requested resource was not found.
             */
            message: string;
          };
        };
      };
    };
    /** @description The server cannot find the requested resource. */
    404: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": {
          error: {
            /**
             * @description A short code indicating the error code returned.
             * @example not_found
             * @enum {string}
             */
            code: "not_found";
            /**
             * @description A human readable explanation of what went wrong.
             * @example The requested resource was not found.
             */
            message: string;
          };
        };
      };
    };
    /** @description This response is sent when a request conflicts with the current state of the server. */
    409: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": {
          error: {
            /**
             * @description A short code indicating the error code returned.
             * @example conflict
             * @enum {string}
             */
            code: "conflict";
            /**
             * @description A human readable explanation of what went wrong.
             * @example The requested resource was not found.
             */
            message: string;
          };
        };
      };
    };
    /** @description This response is sent when the requested content has been permanently deleted from server, with no forwarding address. */
    410: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": {
          error: {
            /**
             * @description A short code indicating the error code returned.
             * @example invite_expired
             * @enum {string}
             */
            code: "invite_expired";
            /**
             * @description A human readable explanation of what went wrong.
             * @example The requested resource was not found.
             */
            message: string;
          };
        };
      };
    };
    /** @description The request was well-formed but was unable to be followed due to semantic errors. */
    422: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": {
          error: {
            /**
             * @description A short code indicating the error code returned.
             * @example unprocessable_entity
             * @enum {string}
             */
            code: "unprocessable_entity";
            /**
             * @description A human readable explanation of what went wrong.
             * @example The requested resource was not found.
             */
            message: string;
          };
        };
      };
    };
    /** @description The user has sent too many requests in a given amount of time ("rate limiting") */
    429: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": {
          error: {
            /**
             * @description A short code indicating the error code returned.
             * @example rate_limit_exceeded
             * @enum {string}
             */
            code: "rate_limit_exceeded";
            /**
             * @description A human readable explanation of what went wrong.
             * @example The requested resource was not found.
             */
            message: string;
          };
        };
      };
    };
    /** @description The server has encountered a situation it does not know how to handle. */
    500: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": {
          error: {
            /**
             * @description A short code indicating the error code returned.
             * @example internal_server_error
             * @enum {string}
             */
            code: "internal_server_error";
            /**
             * @description A human readable explanation of what went wrong.
             * @example The requested resource was not found.
             */
            message: string;
          };
        };
      };
    };
  };
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
