/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/v1/auth/register": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Register a new user */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      /** @description User registration data */
      requestBody: {
        content: {
          "application/json": {
            name: string;
            /** Format: email */
            email: string;
            password: string;
          };
        };
      };
      responses: {
        /** @description User registered successfully */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["AuthTokenResponse"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Login a user */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      /** @description User login data */
      requestBody: {
        content: {
          "application/json": {
            /** Format: email */
            email: string;
            password: string;
          };
        };
      };
      responses: {
        /** @description User logged in successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["AuthTokenResponse"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    AuthTokenResponse: {
      accessToken: string;
    };
    User: {
      id: string;
      name: string;
      /** Format: email */
      email: string;
      /** @enum {string} */
      role: "ADMIN" | "USER";
      /** Format: date-time */
      emailVerified?: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
  };
  responses: {
    /** @description The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing). */
    400: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": {
          error: {
            /**
             * @description A short code indicating the error code returned.
             * @example bad_request
             * @enum {string}
             */
            code: "bad_request";
            /**
             * @description A human readable explanation of what went wrong.
             * @example The requested resource was not found.
             */
            message: string;
          };
        };
      };
    };
    /** @description Although the HTTP standard specifies "unauthorized", semantically this response means "unauthenticated". That is, the client must authenticate itself to get the requested response. */
    401: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": {
          error: {
            /**
             * @description A short code indicating the error code returned.
             * @example unauthorized
             * @enum {string}
             */
            code: "unauthorized";
            /**
             * @description A human readable explanation of what went wrong.
             * @example The requested resource was not found.
             */
            message: string;
          };
        };
      };
    };
    /** @description The client does not have access rights to the content; that is, it is unauthorized, so the server is refusing to give the requested resource. Unlike 401 Unauthorized, the client's identity is known to the server. */
    403: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": {
          error: {
            /**
             * @description A short code indicating the error code returned.
             * @example forbidden
             * @enum {string}
             */
            code: "forbidden";
            /**
             * @description A human readable explanation of what went wrong.
             * @example The requested resource was not found.
             */
            message: string;
          };
        };
      };
    };
    /** @description The server cannot find the requested resource. */
    404: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": {
          error: {
            /**
             * @description A short code indicating the error code returned.
             * @example not_found
             * @enum {string}
             */
            code: "not_found";
            /**
             * @description A human readable explanation of what went wrong.
             * @example The requested resource was not found.
             */
            message: string;
          };
        };
      };
    };
    /** @description This response is sent when a request conflicts with the current state of the server. */
    409: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": {
          error: {
            /**
             * @description A short code indicating the error code returned.
             * @example conflict
             * @enum {string}
             */
            code: "conflict";
            /**
             * @description A human readable explanation of what went wrong.
             * @example The requested resource was not found.
             */
            message: string;
          };
        };
      };
    };
    /** @description This response is sent when the requested content has been permanently deleted from server, with no forwarding address. */
    410: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": {
          error: {
            /**
             * @description A short code indicating the error code returned.
             * @example invite_expired
             * @enum {string}
             */
            code: "invite_expired";
            /**
             * @description A human readable explanation of what went wrong.
             * @example The requested resource was not found.
             */
            message: string;
          };
        };
      };
    };
    /** @description The request was well-formed but was unable to be followed due to semantic errors. */
    422: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": {
          error: {
            /**
             * @description A short code indicating the error code returned.
             * @example unprocessable_entity
             * @enum {string}
             */
            code: "unprocessable_entity";
            /**
             * @description A human readable explanation of what went wrong.
             * @example The requested resource was not found.
             */
            message: string;
          };
        };
      };
    };
    /** @description The user has sent too many requests in a given amount of time ("rate limiting") */
    429: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": {
          error: {
            /**
             * @description A short code indicating the error code returned.
             * @example rate_limit_exceeded
             * @enum {string}
             */
            code: "rate_limit_exceeded";
            /**
             * @description A human readable explanation of what went wrong.
             * @example The requested resource was not found.
             */
            message: string;
          };
        };
      };
    };
    /** @description The server has encountered a situation it does not know how to handle. */
    500: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": {
          error: {
            /**
             * @description A short code indicating the error code returned.
             * @example internal_server_error
             * @enum {string}
             */
            code: "internal_server_error";
            /**
             * @description A human readable explanation of what went wrong.
             * @example The requested resource was not found.
             */
            message: string;
          };
        };
      };
    };
  };
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
